namespace YifySearch.Enums
{
    public enum Genre
    {
        Action,
        Adventure,
        Animation,
        Biography,
        Comedy,
        Crime,
        Documentary,
        Drama,
        Family,
        Fantasy,
        FilmNoir,
        History,
        Horror,
        Music,
        Musical,
        Mystery,
        Romance,
        SciFi,
        ShortFilm,
        Sport,
        Superhero,
        Thriller,
        War,
        Western
    }
}